In [1]:
print("Akshada")

Akshada


In [2]:
import numpy as np

In [4]:
def function1():
    arr = np.array([1,7,13,105])
    print(arr)
    print(f"NBYTES = {arr.nbytes}")

In [5]:
function1()

[  1   7  13 105]
NBYTES = 32


In [8]:
arr1 = np.array([9,5,1]) 
arr2 = np.array([5,9,5]) 
i= arr1.size - 1
while i>=0:
    if arr1[i]>arr2[i]:
        print(f"{arr1[i]} is greater than {arr2[i]}")
    elif arr1[i]<arr2[i]:
        print(f"{arr1[i]} is less than {arr2[i]}")
    elif arr1[i]>=arr2[i]:
        print(f"{arr1[i]} is greater than equal to {arr2[i]}")
    elif arr1[i]<=arr2[i]:
        print(f"{arr1[i]} is less than equal to {arr2[i]}")
    i = i - 1

1 is less than 5
5 is less than 9
9 is greater than 5


In [15]:
arr = np.zeros(10)
print(arr)
arr1 = np.ones(10)
print(arr1)
print(arr1*5)
print(arr1*10)
print(arr1*20)
print(arr1*50)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [16]:
arr1 = np.arange(30,70)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [17]:
arr1 = np.arange(50,95)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [18]:
arr1 = np.arange(20,80,2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [20]:
arr1 = np.arange(21,80,2)
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [23]:
n1 = np.random.randint(10,40,15) # any four random numbers from 10 to 40
print(n1)

[32 15 23 34 25 14 11 39 24 22 13 21 19 20 15]


In [25]:
n1 = np.random.randint(30,50,10) # any four random numbers from 30 to 50
print(n1)

[47 41 45 34 35 43 36 45 48 48]


In [26]:
n1 = np.random.randint(50,90,20) # any four random numbers from 50 to 90
print(n1)

[73 74 69 85 68 83 66 89 56 71 79 83 72 74 50 50 51 89 57 86]


In [28]:
n1 = np.array([9,8,7,6])
n2 = np.array([6,5,4,3])
print(f"N1 = {n1}")
print(f"N2 = {n2}")
print(n1+n2)
print(n1-n2)
print(n1*n2)
a = np.array(n1/n2,dtype=np.int16)
print(a)

N1 = [9 8 7 6]
N2 = [6 5 4 3]
[15 13 11  9]
[3 3 3 3]
[54 40 28 18]
[1 1 1 2]


In [34]:
m = np.arange(10, 22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [35]:
x = np.eye(3)


In [36]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
x = np.eye(5)

In [38]:
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
a = np.random.random((3, 3, 3))

In [40]:
print(a)

[[[0.91539199 0.96763842 0.30359176]
  [0.01712778 0.09983787 0.68267572]
  [0.82654204 0.33863882 0.28669614]]

 [[0.40022175 0.36102944 0.30510201]
  [0.38942141 0.83708305 0.92612848]
  [0.44614025 0.68921486 0.47165197]]

 [[0.57126321 0.97710275 0.59418593]
  [0.64581753 0.70016433 0.69213855]
  [0.85457653 0.86409654 0.05164895]]]


In [41]:
b = np.random.random((2, 3, 4))

In [42]:
print(b)

[[[0.62885221 0.61464174 0.04330766 0.67100825]
  [0.62588116 0.94089712 0.7495799  0.14976635]
  [0.7677826  0.35386515 0.3815712  0.37307759]]

 [[0.84492476 0.30758699 0.25130334 0.50673518]
  [0.56986719 0.73629344 0.1063321  0.20449026]
  [0.43832751 0.86593841 0.33106094 0.49410238]]]


In [43]:
l = [2.5, 1.2, 10, 6.3]

In [44]:
print("original list : ", l)

original list :  [2.5, 1.2, 10, 6.3]


In [45]:
a = np.array(l)


In [46]:
print("one-dimesionaal array : " ,a)

one-dimesionaal array :  [ 2.5  1.2 10.   6.3]


In [47]:
x = np.arange(2, 11).reshape(3, 3)

In [48]:
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [49]:
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [51]:
a = np.arange(12, 38)

In [52]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [54]:
x = np.arange(12, 38)

In [55]:
print("Original array ")
print(x)

Original array 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [56]:
print("Reverse array:")
x = x[::-1]
print(x) 

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [57]:
a = [1, 2, 3, 4]
print("Original array")
print(a)

Original array
[1, 2, 3, 4]


In [59]:
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Array converted to a float type:
[1. 2. 3. 4.]


In [60]:
x = np.arange(7)
print("Original array:")
print(x)

Original array:
[0 1 2 3 4 5 6]


In [61]:
print("Element-wise remainder of division:")
print(np.remainder(x, 5)) 

Element-wise remainder of division:
[0 1 2 3 4 0 1]


In [62]:
numbers = np.arange(20, 51)
divisible_by_3 = numbers[numbers % 3 == 0]
remainder_array = divisible_by_3 % 3
print("Numbers divisible by 3:", divisible_by_3)
print("Element-wise remainder array:", remainder_array)


Numbers divisible by 3: [21 24 27 30 33 36 39 42 45 48]
Element-wise remainder array: [0 0 0 0 0 0 0 0 0 0]
